    SELECT S_ITYPE = '1', S_DEPARTNO =  (CASE WHEN DEPARTMENT.S_NO IS NULL THEN '' ELSE DAY_DPTBUSINESS.S_DEPARTMENT END), S_DEPART = ISNULL(DEPARTMENT.S_DESCRIBE,''), I_SORT = MAX(ISNULL(DEPARTMENT.I_SORT,99)), S_TYPE = ISNULL(DAY_DPTBUSINESS.S_TYPE,DAY_DPTBUSINESS.S_CODE), S_NAME = CASE WHEN RTRIM(LTRIM(ISNULL(BCT_MENU_TYPE.CODE,''))) <> '' THEN BCT_MENU_TYPE.TYPE_REPORT ELSE ISNULL(CHARGE_TYPE.S_DESCRIBE,DAY_DPTBUSINESS.S_TYPE) + CASE WHEN ISNULL(V_CTCODE,'') <> '' THEN '(' + V_CUSTTYPENM + ')' ELSE '' END END, N_DAYCOUNT = SUM(ISNULL(NULLIF(N_TSUM,0),N_COUNT)), N_DAYCHARGE = SUM(ISNULL(N_CHARGE,0)), S_CTCODE = MAX(V_CTCODE), S_ISCY = MAX(CASE WHEN ISNULL(S_DIN_TYPE,'') <> '' THEN 'Y' ELSE 'N' END)
    FROM DAY_DPTBUSINESS LEFT JOIN CHARGE_TYPE ON CHARGE_TYPE.S_TYPE = DAY_DPTBUSINESS.S_TYPE LEFT JOIN DEPARTMENT ON DEPARTMENT.S_NO = DAY_DPTBUSINESS.S_DEPARTMENT LEFT JOIN BCT_MENU_TYPE ON BCT_MENU_TYPE.CODE = DAY_DPTBUSINESS.S_DIN_TYPE LEFT JOIN CUSTTYPES ON CUSTTYPES.S_CODE = DAY_DPTBUSINESS.V_CTCODE
    WHERE DAY_DPTBUSINESS.D_HOTEL_DATE BETWEEN '2017-10-22' and '2017-12-14' AND DAY_DPTBUSINESS.S_DATATYPE = '1' AND DAY_DPTBUSINESS.S_TYPE NOT IN ('SER','DIS')
    GROUP BY (CASE WHEN DEPARTMENT.S_NO IS NULL THEN '' ELSE DAY_DPTBUSINESS.S_DEPARTMENT END), ISNULL(DEPARTMENT.S_DESCRIBE,''),ISNULL(DAY_DPTBUSINESS.S_TYPE,DAY_DPTBUSINESS.S_CODE),CASE WHEN RTRIM(LTRIM(ISNULL(BCT_MENU_TYPE.CODE,''))) <> '' THEN BCT_MENU_TYPE.TYPE_REPORT ELSE ISNULL(CHARGE_TYPE.S_DESCRIBE,DAY_DPTBUSINESS.S_TYPE) + CASE WHEN ISNULL(V_CTCODE,'') <> '' THEN '(' + V_CUSTTYPENM + ')' ELSE '' END END
UNION ALL
    SELECT S_ITYPE = '1', S_DEPARTNO = CASE WHEN DEPARTMENT.S_NO IS NULL THEN '' ELSE DAY_DPTBUSINESS.S_DEPARTMENT END, S_DEPART = ISNULL(DEPARTMENT.S_DESCRIBE,''), I_SORT = MAX(ISNULL(DEPARTMENT.I_SORT,99)), S_TYPE = 'DIS', S_NAME = '折扣', N_DAYCOUNT = 0, N_DAYCHARGE = SUM(DAY_DPTBUSINESS.N_DISC_CHARGE - DAY_DPTBUSINESS.N_CHARGE), S_CTCODE = '', S_ISCY = 'N'
    FROM DAY_DPTBUSINESS LEFT JOIN DEPARTMENT ON DEPARTMENT.S_NO = DAY_DPTBUSINESS.S_DEPARTMENT
    WHERE DAY_DPTBUSINESS.D_HOTEL_DATE BETWEEN '2017-10-22' and '2017-12-14' AND DAY_DPTBUSINESS.S_DATATYPE = '1' AND DAY_DPTBUSINESS.S_TYPE NOT IN ('SER','DIS')
    GROUP BY CASE WHEN DEPARTMENT.S_NO IS NULL THEN '' ELSE DAY_DPTBUSINESS.S_DEPARTMENT END,ISNULL(DEPARTMENT.S_DESCRIBE,'')
UNION ALL
    SELECT S_ITYPE = '1', S_DEPARTNO = 'RAT', S_DEPART = '损益', I_SORT = 99, S_TYPE = 'RAT', S_NAME = '损益', N_DAYCOUNT = 0, N_DAYCHARGE = SUM(N_CHARGE), S_CTCODE = '', S_ISCY = 'N'
    FROM DAY_DPTBUSINESS
    WHERE D_HOTEL_DATE BETWEEN '2017-10-22' and '2017-12-14' AND S_DATATYPE = '3'
UNION ALL
    SELECT S_ITYPE = '2', S_DEPARTNO = 'YY', S_DEPART = '收银合计', I_SORT = 99, S_TYPE = ISNULL(PAY_CODE.S_CODE,DAY_DPTBUSINESS.S_CODE), S_NAME = ISNULL(PAY_CODE.VC_DESCRIBE, DAY_DPTBUSINESS.S_CODE), N_DAYCOUNT = 0, N_DAYCHARGE = SUM(DAY_DPTBUSINESS.N_PAY), S_CTCODE = '', S_ISCY = 'N'
    FROM DAY_DPTBUSINESS LEFT JOIN PAY_CODE ON PAY_CODE.S_CODE = DAY_DPTBUSINESS.S_CODE
    WHERE D_HOTEL_DATE BETWEEN '2017-10-22' and '2017-12-14' AND S_DATATYPE = '2'
    GROUP BY ISNULL(PAY_CODE.S_CODE,DAY_DPTBUSINESS.S_CODE), ISNULL(PAY_CODE.VC_DESCRIBE,DAY_DPTBUSINESS.S_CODE)